**Web Scraping und Data Mining in Python**

# URL und WebAPI

Jan Riebling, *Universität Wuppertal*

# URL

## Allgemein

* Uniform Ressource Locator.
* Gibt die Adresse einer spezifischen Ressource in einem Netzwerk an.
* Kann benutzt werden um Anfragen an Server zu stellen.
* Allgemeine Form:  
```
scheme://domain:port/path?query_string#fragment_id
```

## HyperText Transfer Protocol

HTTP und HTTPS spezifizieren den Datenaustausch zwischen Client (meistens der Browser) und einem Server über das TCP/IP System.

Technische Spezifikation: [RFC2616](https://datatracker.ietf.org/doc/html/rfc2616.html).

## `urllib`

Python Standardbibliothek zum Umgang mit URLs. Für diesen Workshop sind insbesondere die Funktionen in `urllib.request` von Bedeutung, da sich hiermit Anfragen an Server stellen lassen.

## Beispiel

`urllib.request.urlopen` nimmt als Argument eine URL, schickt einen GET Request an den Server und gibt dessen Antwort zurück.

In [1]:
from urllib.request import urlopen

url = 'https://www.uni-mainz.de/'

response = urlopen(url)

In [2]:
response

# Application Programming Interface

## API

* Schnittstelle zur Interaktion zwischen Programmen oder Programmen und Servern.
* WebAPIs:
    * Abruf/Veränderung von Ressourcen (GET vs. POST).
    * Client-Server Beziehung.
    * Vermittelt durch HTTP.
    * Daten meist in Form der Webstandards für Dokumente (z.B. JSON oder XML).
* Für viele APIs ist eine vorherige Anmeldung notwendig. Hier sind unbedingt die ToS zu beachten!
* API Verzeichnis: https://www.programmableweb.com/

##  Funktionsweise

* Aufbau einer HTTP Anfrage entsprechend dem URL Schema.
    * Konkrete Anfrage geschieht über `?query_string`.
    * Übersetzung von Programmcode in die spezifische Anfrage
* Änderung des Zustands des Servers oder Abrufen von Daten
* Übersetzung der Daten in Elemente der Programmumgebung

# Beispiel: World Bank Indicators 

* Offen zugängliche Datensätze der Weltbank.
* Dokumentation: [http://data.worldbank.org/developers/api-overview](http://data.worldbank.org/developers/api-overview).
* Python Module:
    * `py-worldbank`.
    * `wbpy`.
    * `pandas_datareader`.

In [41]:
jsondata = urlopen('http://api.worldbank.org/v2/country/deu;usa;fra/indicator/SP.POP.TOTL?date=2000:2010&format=json').read()

In [46]:
import json

json.loads(jsondata)

[{'page': 1,
  'pages': 1,
  'per_page': 50,
  'total': 33,
  'sourceid': '2',
  'sourcename': 'World Development Indicators',
  'lastupdated': '2022-02-15'},
 [{'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'DE', 'value': 'Germany'},
   'countryiso3code': 'DEU',
   'date': '2010',
   'value': 81776930,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'DE', 'value': 'Germany'},
   'countryiso3code': 'DEU',
   'date': '2009',
   'value': 81902307,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'DE', 'value': 'Germany'},
   'countryiso3code': 'DEU',
   'date': '2008',
   'value': 82110097,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'DE', 'value': 'Germany'},
   'countryiso3code': 'DEU',
   'date': '2007',
   'value': 82266372,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'DE', 'value': 'Germany'},
   'countryiso3code': 'DEU',
   'date': '2006',
   'value': 82376451,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'DE', 'value': 'Germany'},
   'countryiso3code': 'DEU',
   'date': '2005',
   'value': 82469422,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'DE', 'value': 'Germany'},
   'countryiso3code': 'DEU',
   'date': '2004',
   'value': 82516260,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'DE', 'value': 'Germany'},
   'countryiso3code': 'DEU',
   'date': '2003',
   'value': 82534176,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'DE', 'value': 'Germany'},
   'countryiso3code': 'DEU',
   'date': '2002',
   'value': 82488495,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'DE', 'value': 'Germany'},
   'countryiso3code': 'DEU',
   'date': '2001',
   'value': 82349925,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'DE', 'value': 'Germany'},
   'countryiso3code': 'DEU',
   'date': '2000',
   'value': 82211508,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'FR', 'value': 'France'},
   'countryiso3code': 'FRA',
   'date': '2010',
   'value': 65027505,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'FR', 'value': 'France'},
   'countryiso3code': 'FRA',
   'date': '2009',
   'value': 64707035,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'FR', 'value': 'France'},
   'countryiso3code': 'FRA',
   'date': '2008',
   'value': 64374979,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'FR', 'value': 'France'},
   'countryiso3code': 'FRA',
   'date': '2007',
   'value': 64016227,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'FR', 'value': 'France'},
   'countryiso3code': 'FRA',
   'date': '2006',
   'value': 63621376,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'FR', 'value': 'France'},
   'countryiso3code': 'FRA',
   'date': '2005',
   'value': 63179356,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'FR', 'value': 'France'},
   'countryiso3code': 'FRA',
   'date': '2004',
   'value': 62704901,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'FR', 'value': 'France'},
   'countryiso3code': 'FRA',
   'date': '2003',
   'value': 62244880,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'FR', 'value': 'France'},
   'countryiso3code': 'FRA',
   'date': '2002',
   'value': 61805266,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'FR', 'value': 'France'},
   'countryiso3code': 'FRA',
   'date': '2001',
   'value': 61357432,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'FR', 'value': 'France'},
   'countryiso3code': 'FRA',
   'date': '2000',
   'value': 60912500,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'US', 'value': 'United States'},
   'countryiso3code': 'USA',
   'date': '2010',
   'value': 309327143,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'US', 'value': 'United States'},
   'countryiso3code': 'USA',
   'date': '2009',
   'value': 306771529,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'US', 'value': 'United States'},
   'countryiso3code': 'USA',
   'date': '2008',
   'value': 304093966,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'US', 'value': 'United States'},
   'countryiso3code': 'USA',
   'date': '2007',
   'value': 301231207,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'US', 'value': 'United States'},
   'countryiso3code': 'USA',
   'date': '2006',
   'value': 298379912,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'US', 'value': 'United States'},
   'countryiso3code': 'USA',
   'date': '2005',
   'value': 295516599,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'US', 'value': 'United States'},
   'countryiso3code': 'USA',
   'date': '2004',
   'value': 292805298,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'US', 'value': 'United States'},
   'countryiso3code': 'USA',
   'date': '2003',
   'value': 290107933,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'US', 'value': 'United States'},
   'countryiso3code': 'USA',
   'date': '2002',
   'value': 287625193,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'US', 'value': 'United States'},
   'countryiso3code': 'USA',
   'date': '2001',
   'value': 284968955,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'country': {'id': 'US', 'value': 'United States'},
   'countryiso3code': 'USA',
   'date': '2000',
   'value': 282162411,
   'unit': '',
   'obs_status': '',
   'decimal': 0}]]

## API Wrappers

Zwar ist es immer möglich eine direkte Anfrage an den Server zu schicken (z.B. mittels Pythons `urllib` Bibliothek), doch in vielen Fällen bietet sich die einfachere Variante an einen bereits bestehenden "Wrapper" zu benutzen. Dabei handelt es sich um Python-Code, der die Interaktion mit der API übernimmt. Um einen solchen Wrapper zu finden ist es meistens ausreichend eine Suchanfrage der Art:

```
<Name der Anwendung> python api
```

zu stellen.

## Beispiel: World Bank Indicators Wrapper

In [1]:
import pandas as pd
from pandas_datareader import wb

## DataFrame of all indicators:
ind_df = wb.get_indicators()

In [2]:
ind_df.columns

Index(['id', 'name', 'unit', 'source', 'sourceNote', 'sourceOrganization',
       'topics'],
      dtype='object')

## Viewing DataFrames

A representation (view) of the DataFrame can be called by returning the object or through printing. For bigger datasets this view will be shortened in order to prevent memory hangups. The first and last rows can be viewed through `.head()` and `.tail()`.

All parts of the DataFrame are represented as attributes and can be accessed as such:

* `df.columns`
* `df.index`
* `df.values`

In [3]:
ind_df.head()

,id,name,unit,source,sourceNote,sourceOrganization,topics
0,1.0.HCount.1.90usd,Poverty Headcount ($1.90 a day),,LAC Equity Lab,The poverty headcount index measures the propo...,b'LAC Equity Lab tabulations of SEDLAC (CEDLAS...,Poverty
1,1.0.HCount.2.5usd,Poverty Headcount ($2.50 a day),,LAC Equity Lab,The poverty headcount index measures the propo...,b'LAC Equity Lab tabulations of SEDLAC (CEDLAS...,Poverty
2,1.0.HCount.Mid10to50,Middle Class ($10-50 a day) Headcount,,LAC Equity Lab,The poverty headcount index measures the propo...,b'LAC Equity Lab tabulations of SEDLAC (CEDLAS...,Poverty
3,1.0.HCount.Ofcl,Official Moderate Poverty Rate-National,,LAC Equity Lab,The poverty headcount index measures the propo...,b'LAC Equity Lab tabulations of data from Nati...,Poverty
4,1.0.HCount.Poor4uds,Poverty Headcount ($4 a day),,LAC Equity Lab,The poverty headcount index measures the propo...,b'LAC Equity Lab tabulations of SEDLAC (CEDLAS...,Poverty

## Durchsuchen 

Pandas `.str.` Notation kann genutzt werden um nach Variablen Namen zu suchen.

In [12]:
ind_df[ind_df['name'].str.contains(r'[Aa]gricult')]

,id,name,source,sourceNote,sourceOrganization,topics
119,3.01.04.01.agcen,Agricultural census,Statistical Capacity Indicators,Agricultural censuses collect information on a...,b'World Bank: Microdata library. Original sour...,
973,AG.AGR.TRAC.NO,"Agricultural machinery, tractors",World Development Indicators,Agricultural machinery refers to the number of...,"b'Food and Agriculture Organization, electroni...",Agriculture & Rural Development
998,AG.LND.AGRI.HA,Agricultural land (hectares),Africa Development Indicators,Agricultural land refers to the share of land ...,"b'Food and Agriculture Organization, electroni...",
999,AG.LND.AGRI.K2,Agricultural land (sq. km),World Development Indicators,Agricultural land refers to the share of land ...,"b'Food and Agriculture Organization, electroni...",Agriculture & Rural Development ; Climate Ch...
1000,AG.LND.AGRI.ZS,Agricultural land (% of land area),World Development Indicators,Agricultural land refers to the share of land ...,"b'Food and Agriculture Organization, electroni...",Agriculture & Rural Development ; Climate Ch...
1019,AG.LND.IRIG.AG.ZS,Agricultural irrigated land (% of total agricu...,World Development Indicators,Agricultural irrigated land refers to agricult...,"b'Food and Agriculture Organization, electroni...",Agriculture & Rural Development ; Climate Ch...
1021,AG.LND.IRIG.HA.AG,Agricultural area irrigated (ha),Africa Development Indicators,"Agricultural area irrigated, part of the full ...","b'Food and Agriculture Organization, electroni...",
1036,AG.LND.TRAC.ZS,"Agricultural machinery, tractors per 100 sq. k...",World Development Indicators,Agricultural machinery refers to the number of...,"b'Food and Agriculture Organization, electroni...",Agriculture & Rural Development
1038,AG.PRD.AGRI.XD,Agriculture production index (1999-2001 = 100),Africa Development Indicators,The FAO indices of agricultural production sho...,"b'Food and Agriculture Organization, electroni...",
1045,AG.PRD.GAGRI.XD,"Agriculture production index (gross, 1999-2001...",Africa Development Indicators,The FAO indices of agricultural production sho...,"b'Food and Agriculture Organization, electroni...",
1069,AG.TRC.EMPL.ZS,"Agricultural machinery, tractors per agricultu...",WDI Database Archives,,b'',
1465,BM.AG.AGR.TRAC.CD,"Agricultural tractors, exports (FAO, current US$)",Africa Development Indicators,Agricultural machinery refers to the number of...,"b'Food and Agriculture Organization, electroni...",
1466,BM.AG.AGR.TRAC.NO,"Agricultural tractors, exports",Africa Development Indicators,Agricultural machinery refers to the number of...,"b'Food and Agriculture Organization, electroni...",
1473,BM.GSR.AGRI.CD,"Total agricultural imports (FAO, current US$)",Africa Development Indicators,Total agricultural imports are expressed in te...,"b'Food and Agriculture Organization, electroni...",
1561,BX.AG.AGR.TRAC.CD,"Agricultural tractors, imports (FAO, current US$)",Africa Development Indicators,Agricultural machinery refers to the number of...,"b'Food and Agriculture Organization, electroni...",
1562,BX.AG.AGR.TRAC.NO,"Agricultural tractors, imports",Africa Development Indicators,Agricultural machinery refers to the number of...,"b'Food and Agriculture Organization, electroni...",
1573,BX.GSR.AGRI.CD,"Total agricultural exports (FAO, current US$)",Africa Development Indicators,Total agricultural imports are expressed in te...,"b'Food and Agriculture Organization, electroni...",
1676,DAK.AGR.CR,Total Specific Allocation Grant for Agricultur...,Indonesia Database for Policy and Economic Res...,,"b'Ministry of Finance, Ministry of Finance Reg...",
4325,DT.ODA.DACD.PROD.AGRI.AGR.CD,"Gross ODA aid disbursement for agriculture, DA...",Africa Development Indicators,This is described as agricultural policy and a...,b'Development Assistance Committee of the Orga...,
4326,DT.ODA.DACD.PROD.AGRI.CD,"Gross ODA aid disbursement for agriculture, fo...",Africa Development Indicators,This is the aggregate total for agriculture (D...,b'Development Assistance Committee of the Orga...,
4787,EA.AGR.TOTL.IN.ZS,Agricultural land per worker (hectares),WDI Database Archives,,b'',
4790,EA.PRD.AGRI.KD,Agriculture value added per worker (constant 2...,World Development Indicators,Agriculture value added per worker is a measur...,b'Derived from World Bank national accounts fi...,Agriculture & Rural Development
4791,EA.PRD.LAND.KD,Agriculture value added per hectare of agricul...,WDI Database Archives,,b'',
4852,EN.AGR.EMPL,Economically active population in agriculture ...,Africa Development Indicators,Agricultural employment shows the number of wo...,"b'Food and Agriculture Organization, Productio...",Agriculture & Rural Development
4853,EN.AGR.EMPL.FE,"Economically active population in agriculture,...",Africa Development Indicators,Economically active female population in agric...,"b'Food and Agriculture Organization, electroni...",
4854,EN.AGR.EMPL.IN,"Agricultural population (FAO, number)",Africa Development Indicators,The Agricultural Population is defined as all ...,"b'Food and Agriculture Organization, electroni...",
4855,EN.AGR.EMPL.MA,"Economically active population in agriculture,...",Africa Development Indicators,Economically active male population in agricul...,"b'Food and Agriculture Organization, electroni...",
4881,EN.ATM.METH.AG.KT.CE,Agricultural methane emissions (thousand metri...,World Development Indicators,Agricultural methane emissions are emissions f...,"b'European Commission, Joint Research Centre (...",Agriculture & Rural Development ; Environment
4882,EN.ATM.METH.AG.ZS,Agricultural methane emissions (% of total),World Development Indicators,Agricultural methane emissions are emissions f...,b'World Bank staff estimates from original sou...,Agriculture & Rural Development ; Environment
4889,EN.ATM.NOXE.AG.KT.CE,Agricultural nitrous oxide emissions (thousand...,World Development Indicators,Agricultural nitrous oxide emissions are emiss...,"b'European Commission, Joint Research Centre (...",Agriculture & Rural Development ; Environment
...,...,...,...,...,...,...
10816,TM.TAX.AGRI.CD.LD,Average tariffs imposed by developed countries...,Millennium Development Goals,It is the average tariffs imposed by developed...,b'United Nations Conference on Trade and Devel...,Millenium development goals
10854,TM.VAL.AGRI.ZS.UN,Agricultural raw materials imports (% of merch...,World Development Indicators,Agricultural raw materials comprise SITC secti...,b'World Bank staff estimates through the WITS ...,Agriculture & Rural Development ; Private Se...
10962,TX.VAL.AGRI.ZS.UN,Agricultural raw materials exports (% of merch...,World Development Indicators,Agricultural raw materials comprise SITC secti...,b'World Bank staff estimates through the WITS ...,Agriculture & Rural Development ; Private Se...
11334,UIS.FEP.56.F600,Percentage of students enrolled in Agriculture...,Education Statistics,Total number of female students in a given ter...,b'UNESCO Institute for Statistics',
11365,UIS.FOSEP.56.F600,Percentage of students in tertiary education e...,Education Statistics,Percentage of all tertiary students who are en...,b'UNESCO Institute for Statistics',Education
11366,UIS.FOSEP.56.F600.F,Percentage of female students in tertiary educ...,Education Statistics,Percentage of all female tertiary students who...,b'UNESCO Institute for Statistics',Education
11367,UIS.FOSEP.56.F600.M,Percentage of male students in tertiary educat...,Education Statistics,Percentage of all male tertiary students who a...,b'UNESCO Institute for Statistics',
11382,UIS.FOSGP.56.F600.M,Percentage of male graduates from tertiary edu...,Education Statistics,Share of all male tertiary graduates who compl...,b'UNESCO Institute for Statistics',
12305,WP11659.1,Purchased agriculture insurance (% working in ...,Global Financial Inclusion,Denotes the percentage of respondents who are ...,"b'Demirguc-Kunt and Klapper, 2012'",Financial Sector
12837,WP15184.1,Received payments for agricultural products in...,Global Financial Inclusion,Denotes the percentage of respondents who repo...,"b'Demirguc-Kunt et al., 2015'",Financial Sector
12838,WP15184.10,Received payments for agricultural products in...,Global Financial Inclusion,Denotes the percentage of respondents who repo...,"b'Demirguc-Kunt et al., 2015'",Financial Sector
12839,WP15184.2,Received payments for agricultural products in...,Global Financial Inclusion,Denotes the percentage of respondents who repo...,"b'Demirguc-Kunt et al., 2015'",Financial Sector
12840,WP15184.3,Received payments for agricultural products in...,Global Financial Inclusion,Denotes the percentage of respondents who repo...,"b'Demirguc-Kunt et al., 2015'",Financial Sector
12841,WP15184.4,Received payments for agricultural products in...,Global Financial Inclusion,Denotes the percentage of respondents who repo...,"b'Demirguc-Kunt et al., 2015'",Financial Sector
12842,WP15184.5,Received payments for agricultural products in...,Global Financial Inclusion,Denotes the percentage of respondents who repo...,"b'Demirguc-Kunt et al., 2015'",Financial Sector
12843,WP15184.6,Received payments for agricultural products in...,Global Financial Inclusion,Denotes the percentage of respondents who repo...,"b'Demirguc-Kunt et al., 2015'",Financial Sector
12844,WP15184.7,Received payments for agricultural products in...,Global Financial Inclusion,Denotes the percentage of respondents who repo...,"b'Demirguc-Kunt et al., 2015'",Financial Sector
12845,WP15184.8,Received payments for agricultural products in...,Global Financial Inclusion,Denotes the percentage of respondents who repo...,"b'Demirguc-Kunt et al., 2015'",Financial Sector
12846,WP15184.9,Received payments for agricultural products in...,Global Financial Inclusion,Denotes the percentage of respondents who repo...,"b'Demirguc-Kunt et al., 2015'",Financial Sector
12847,WP15185.1,Received payments for agricultural products: i...,Global Financial Inclusion,"Denotes, among respondents reporting personall...","b'Demirguc-Kunt et al., 2015'",Financial Sector
12848,WP15186.1,Received payments for agricultural products: i...,Global Financial Inclusion,"Denotes, among respondents reporting personall...","b'Demirguc-Kunt et al., 2015'",Financial Sector
12849,WP15187.1,Received payments for agricultural products: t...,Global Financial Inclusion,"Denotes, among respondents reporting personall...","b'Demirguc-Kunt et al., 2015'",Financial Sector
12944,ccx_agr_pop_eld,Share of employed in agriculture - elderly,The Atlas of Social Protection: Indicators of ...,NULL,b'The Atlas of Social Protection: Indicators o...,Social Protection & Labor
12945,ccx_agr_pop_fem,Share of employed in agriculture - female,The Atlas of Social Protection: Indicators of ...,NULL,b'The Atlas of Social Protection: Indicators o...,Social Protection & Labor
12946,ccx_agr_pop_mal,Share of employed in agriculture - male,The Atlas of Social Protection: Indicators of ...,NULL,b'The Atlas of Social Protection: Indicators o...,Social Protection & Labor
12947,ccx_agr_pop_rur,Share of employed in agriculture - rural,The Atlas of Social Protection: Indicators of ...,NULL,b'The Atlas of Social Protection: Indicators o...,Social Protection & Labor
12948,ccx_agr_pop_tot,Share of employed in agriculture -total popula...,The Atlas of Social Protection: Indicators of ...,NULL,b'The Atlas of Social Protection: Indicators o...,Social Protection & Labor
12949,ccx_agr_pop_urb,Share of employed in agriculture - urban,The Atlas of Social Protection: Indicators of ...,NULL,b'The Atlas of Social Protection: Indicators o...,Social Protection & Labor
12950,ccx_agr_pop_wrk,Share of employed in agriculture - working age,The Atlas of Social Protection: Indicators of ...,NULL,b'The Atlas of Social Protection: Indicators o...,Social Protection & Labor
12951,ccx_agr_pop_you,Share of employed in agriculture - youth,The Atlas of Social Protection: Indicators of ...,NULL,b'The Atlas of Social Protection: Indicators o...,Social Protection & Labor

## Daten herunterladen

In [6]:
## Select some indicators
ind = ['NY.GDP.PCAP.KD', 
       'IT.MOB.COV.ZS', 
       'SP.RUR.TOTL.ZS']

df = wb.download(indicator=ind,
                 country='all',
                 start=2001,
                 end=2011)

In [10]:
df

                                     NY.GDP.PCAP.KD  IT.MOB.COV.ZS  \
country                        year
Arab World                     2011     5989.899176            NaN
                               2010     5917.245724            NaN
                               2009     5784.690614            NaN
                               2008     5898.885250            NaN
                               2007     5713.955066            NaN
                               2006     5599.102508            NaN
                               2005     5382.993750            NaN
                               2004     5208.602873            NaN
                               2003     4870.031225            NaN
                               2002     4724.645810            NaN
                               2001     4795.152767            NaN
Caribbean small states         2011     9075.822740            NaN
                               2010     9039.288633            NaN
                               2009     8970.525520            NaN
                               2008     9355.413993            NaN
                               2007     9295.101868            NaN
                               2006     9069.133411            NaN
                               2005     8558.331571            NaN
                               2004     8308.298071            NaN
                               2003     8038.204641            NaN
                               2002     7654.439305            NaN
                               2001     7429.498142            NaN
Central Europe and the Baltics 2011    13005.623153            NaN
                               2010    12556.491605            NaN
                               2009    12300.302177            NaN
                               2008    12722.768195            NaN
                               2007    12217.934898            NaN
                               2006    11441.213370            NaN
                               2005    10708.729281            NaN
                               2004    10177.600139            NaN
...                                             ...            ...
Uganda                         2008             NaN          100.0
                               2007             NaN           80.0
                               2006             NaN           80.0
                               2005             NaN           70.0
                               2004             NaN           75.0
                               2003             NaN           46.0
                               2002             NaN           35.0
                               2001             NaN           22.0
Zambia                         2011             NaN           62.0
                               2010             NaN           90.0
                               2009             NaN           90.0
                               2008             NaN           85.0
                               2007             NaN           78.0
                               2006             NaN           46.0
                               2005             NaN           65.0
                               2004             NaN           50.5
                               2003             NaN           50.5
                               2002             NaN           50.5
                               2001             NaN           50.5
Zimbabwe                       2011             NaN           72.4
                               2010             NaN           61.0
                               2009             NaN           41.0
                               2008             NaN           75.0
                               2007             NaN           75.0
                               2006             NaN           72.0
                               2005             NaN           70.0
                               2004             NaN            NaN
                               2003             NaN            NaN
                               2002             NaN            NaN
                               2001             NaN            NaN

                                     SP.RUR.TOTL.ZS
country                        year
Arab World                     2011       43.330359
                               2010       43.681892
                               2009       44.114470
                               2008       44.548919
                               2007       44.984331
                               2006       45.274258
                               2005       45.674088
                               2004       46.041090
                               2003       46.346152
                               2002       46.631232
                               2001       46.895235
Caribbean small states         2011       49.518268
                               2010       49.543714
                               2009       49.552971
                               2008       49.563265
                               2007       49.576646
                               2006       49.590824
                               2005       49.605562
                               2004       49.620307
                               2003       49.644430
                               2002       49.669601
                               2001       49.709923
Central Europe and the Baltics 2011       37.936066
                               2010       37.981977
                               2009       38.022218
                               2008       38.083895
                               2007       38.166728
                               2006       38.244963
                               2005       38.306482
                               2004       38.361288
...                                             ...
Uganda                         2008             NaN
                               2007             NaN
                               2006             NaN
                               2005             NaN
                               2004             NaN
                               2003             NaN
                               2002             NaN
                               2001             NaN
Zambia                         2011             NaN
                               2010             NaN
                               2009             NaN
                               2008             NaN
                               2007             NaN
                               2006             NaN
                               2005             NaN
                               2004             NaN
                               2003             NaN
                               2002             NaN
                               2001             NaN
Zimbabwe                       2011             NaN
                               2010             NaN
                               2009             NaN
                               2008             NaN
                               2007             NaN
                               2006             NaN
                               2005             NaN
                               2004             NaN
                               2003             NaN
                               2002             NaN
                               2001             NaN

[3564 rows x 3 columns]

In [15]:
## Indikatorinformationen zurückspielen.
## .isin() prüft Elemente in einer Liste.

ind_df[ind_df.id.isin(ind)]

,id,name,source,sourceNote,sourceOrganization,topics,unit
6412,IT.MOB.COV.ZS,Population coverage of mobile cellular telepho...,Africa Development Indicators,Please cite the International Telecommunicatio...,"b'International Telecommunication Union, World...",,
7880,NY.GDP.PCAP.KD,GDP per capita (constant 2010 US$),World Development Indicators,GDP per capita is gross domestic product divid...,"b'World Bank national accounts data, and OECD ...",Economy & Growth,
10498,SP.RUR.TOTL.ZS,Rural population (% of total population),World Development Indicators,Rural population refers to people living in ru...,"b""World Bank staff estimates based on the Unit...",Agriculture & Rural Development,

#  Caveat: MultiIndex

In addition to selection using columns and rows a DataFrame with a MultiIndex provides different levels with which to select from the Index.

In [18]:
df

                                     GDP_per_capita  Cell_coverage  \
country                        year
Arab World                     2011     5989.899176            NaN
                               2010     5917.245724            NaN
                               2009     5784.690614            NaN
                               2008     5898.885250            NaN
                               2007     5713.955066            NaN
                               2006     5599.102508            NaN
                               2005     5382.993750            NaN
                               2004     5208.602873            NaN
                               2003     4870.031225            NaN
                               2002     4724.645810            NaN
                               2001     4795.152767            NaN
Caribbean small states         2011     9075.822740            NaN
                               2010     9039.288633            NaN
                               2009     8970.525520            NaN
                               2008     9355.413993            NaN
                               2007     9295.101868            NaN
                               2006     9069.133411            NaN
                               2005     8558.331571            NaN
                               2004     8308.298071            NaN
                               2003     8038.204641            NaN
                               2002     7654.439305            NaN
                               2001     7429.498142            NaN
Central Europe and the Baltics 2011    13005.623153            NaN
                               2010    12556.491605            NaN
                               2009    12300.302177            NaN
                               2008    12722.768195            NaN
                               2007    12217.934898            NaN
                               2006    11441.213370            NaN
                               2005    10708.729281            NaN
                               2004    10177.600139            NaN
...                                             ...            ...
Uganda                         2008             NaN          100.0
                               2007             NaN           80.0
                               2006             NaN           80.0
                               2005             NaN           70.0
                               2004             NaN           75.0
                               2003             NaN           46.0
                               2002             NaN           35.0
                               2001             NaN           22.0
Zambia                         2011             NaN           62.0
                               2010             NaN           90.0
                               2009             NaN           90.0
                               2008             NaN           85.0
                               2007             NaN           78.0
                               2006             NaN           46.0
                               2005             NaN           65.0
                               2004             NaN           50.5
                               2003             NaN           50.5
                               2002             NaN           50.5
                               2001             NaN           50.5
Zimbabwe                       2011             NaN           72.4
                               2010             NaN           61.0
                               2009             NaN           41.0
                               2008             NaN           75.0
                               2007             NaN           75.0
                               2006             NaN           72.0
                               2005             NaN           70.0
                               2004             NaN            NaN
                               2003             NaN            NaN
                               2002             NaN            NaN
                               2001             NaN            NaN

                                     Rural_population
country                        year
Arab World                     2011         43.330359
                               2010         43.681892
                               2009         44.114470
                               2008         44.548919
                               2007         44.984331
                               2006         45.274258
                               2005         45.674088
                               2004         46.041090
                               2003         46.346152
                               2002         46.631232
                               2001         46.895235
Caribbean small states         2011         49.518268
                               2010         49.543714
                               2009         49.552971
                               2008         49.563265
                               2007         49.576646
                               2006         49.590824
                               2005         49.605562
                               2004         49.620307
                               2003         49.644430
                               2002         49.669601
                               2001         49.709923
Central Europe and the Baltics 2011         37.936066
                               2010         37.981977
                               2009         38.022218
                               2008         38.083895
                               2007         38.166728
                               2006         38.244963
                               2005         38.306482
                               2004         38.361288
...                                               ...
Uganda                         2008               NaN
                               2007               NaN
                               2006               NaN
                               2005               NaN
                               2004               NaN
                               2003               NaN
                               2002               NaN
                               2001               NaN
Zambia                         2011               NaN
                               2010               NaN
                               2009               NaN
                               2008               NaN
                               2007               NaN
                               2006               NaN
                               2005               NaN
                               2004               NaN
                               2003               NaN
                               2002               NaN
                               2001               NaN
Zimbabwe                       2011               NaN
                               2010               NaN
                               2009               NaN
                               2008               NaN
                               2007               NaN
                               2006               NaN
                               2005               NaN
                               2004               NaN
                               2003               NaN
                               2002               NaN
                               2001               NaN

[3564 rows x 3 columns]

In [26]:
## Selecting specific levels via .xs
## Only the year 2011:
df.xs('European Union', level='country')

      GDP_per_capita  Cell_coverage  Rural_population
year
2011    34279.107501            NaN         25.776954
2010    33677.002643            NaN         25.995514
2009    33056.426081            NaN         26.218004
2008    34663.286787            NaN         26.439156
2007    34626.921433            NaN         26.669236
2006    33723.542783            NaN         26.900341
2005    32753.293496            NaN         27.128921
2004    32203.566959            NaN         27.358844
2003    31522.189349            NaN         27.587616
2002    31228.060098            NaN         27.819386
2001    30888.616809            NaN         28.057449

In [51]:
## Most methods take an aditional 
## level argument.

df['GDP_per_capita']

country                         year
Arab World                      2011     5989.899176
                                2010     5917.245724
                                2009     5784.690614
                                2008     5898.885250
                                2007     5713.955066
                                2006     5599.102508
                                2005     5382.993750
                                2004     5208.602873
                                2003     4870.031225
                                2002     4724.645810
                                2001     4795.152767
Caribbean small states          2011     9075.822740
                                2010     9039.288633
                                2009     8970.525520
                                2008     9355.413993
                                2007     9295.101868
                                2006     9069.133411
                                2005     8558.331571
                                2004     8308.298071
                                2003     8038.204641
                                2002     7654.439305
                                2001     7429.498142
Central Europe and the Baltics  2011    13005.623153
                                2010    12556.491605
                                2009    12300.302177
                                2008    12722.768195
                                2007    12217.934898
                                2006    11441.213370
                                2005    10708.729281
                                2004    10177.600139
                                            ...
Uganda                          2008             NaN
                                2007             NaN
                                2006             NaN
                                2005             NaN
                                2004             NaN
                                2003             NaN
                                2002             NaN
                                2001             NaN
Zambia                          2011             NaN
                                2010             NaN
                                2009             NaN
                                2008             NaN
                                2007             NaN
                                2006             NaN
                                2005             NaN
                                2004             NaN
                                2003             NaN
                                2002             NaN
                                2001             NaN
Zimbabwe                        2011             NaN
                                2010             NaN
                                2009             NaN
                                2008             NaN
                                2007             NaN
                                2006             NaN
                                2005             NaN
                                2004             NaN
                                2003             NaN
                                2002             NaN
                                2001             NaN
Name: GDP_per_capita, Length: 3564, dtype: float64

## Weitere Informationen

Im Bezug auf normale [Indizes](http://pandas.pydata.org/pandas-docs/stable/indexing.html) und für [MultiIndizes](http://pandas.pydata.org/pandas-docs/stable/advanced.html) finden sich in der Pandas Dokumentation.

# Weitere API Wrapper

## Einfach googeln

"Name der Plattform + Python + API" reicht meistens aus.

Viele APIs erfordern heute eine Registrierung und eine Authentifizierung.